### ISSUE TITLE
Dsiable non-working tests

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/crypto3-codec#28]

**Comment by kotelifelif** [comment]
basic_components - build
basic_components_r1cs_gg_ppzksnark - build
merkle_tree_components - build

**Comment by kotelifelif** [comment]
Не понятно как собирать logic

**Comment by kotelifelif** [comment]
base - run
hex - run

**Comment by nkaskov** [comment]
Tests codec and hex compile and pass. Other tests we don't have.
